### ISSUE TITLE
Can't login by TOTP

### ISSUE THREAD

**Issue by vuducanha2** [Zimbra-Community/zimbra-foss-2fa#10]
Dear @barrydegraaff ! 
Thanks for suport , but I install 2FA following your guide and i have a new problem  ! 
I can login by App password but **can`t login with TOTP** . 
When i run ldapseach but not authenticate
```
[root@mail ~]# ldapsearch -x -H ldap://172.18.0.2:1389 -D uid=user2,ou=people,dc=viettel,dc=com,dc=vn -w "123456861278" "mail=*"
ldap_bind: Invalid credentials (49)
	additional info: Failed to authenticate.
```
and 
```
[root@mail app]# curl -d "user=user2&pass=123456947075" -X POST https://10.60.156.24:5000/validate/check -k
{"jsonrpc": "2.0", "signature": "3501765228653364556138422784418874681374947869319598582403588589433150706126312916429358286529865640897567099681404570211336416603934098869843834440170867264984927136935081616912786901978756514753485285699394312711619186749690603355488642752877934816266450407029425030220232017508734558965583349951691101267615185314008534792851945280666289831358189142766845892743736499490290494955802903871179784101029846807419999248771262613219887440420695622567293677130568156918332362329836000088644151819705578911107392812691158754733490020922367312384151322834123969037519218045808436409134154648471526828872599372531124913135", "detail": {"message": "wrong otp value", "type": "totp", "serial": "TOTP0001DCC3", "otplen": 6, "threadid": 139695201851200}, "versionnumber": "2.23.4", "version": "privacyIDEA 2.23.4", "result": {"status": true, "value": false}, "time": 1561014110.667295, "id": 1}[root@mail app]# timed out waiting for input: auto-logout

```
Pls help me. Thanks you

P/S: How can i donate for you ?

**Comment by barrydegraaff** [comment]
Make sure the time is correct on your server and phone. 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by vuducanha2** [comment]
It OK.
Thanks you so much.
How can i donate for you ?

**Comment by barrydegraaff** [comment]
You can donate via PayPal. [ mailto:info@barrydegraaff.tk | info@barrydegraaff.tk ] 

Thanks! 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0
