### ISSUE TITLE
2FA is not enforced

### ISSUE THREAD

**Issue by acsiki** [Zimbra-Community/zimbra-foss-2fa#11]
Hello,

I have just installed now the Zimbra FOSS Two Factor Authentication. Works fine if I enable the 2FA and use the code from the mobile authenticator, but works fine as well if I don't use it.

Ex: I can login with admin account on webclient with 2FA and even without.

My zimbra version is 8.8.15

Do I need to enforce somehow the authentication with 2FA?

Thank you.

Kind regards,

Cristian

**Comment by barrydegraaff** [comment]
Admin account and 2FA

At this time, Zimbra will still allow using only a password for admin accounts, this is a bug. 
See https://github.com/Zimbra/zm-mailbox/pull/448 and https://bugzilla.zimbra.com/show_bug.cgi?id=80485 this means, 
you need to create a separate admin account, put a long password on it, and don't use it for day-to-day work.

Also:
https://github.com/Zimbra-Community/zimbra-foss-2fa/blob/master/README-MANUAL-INSTALL.md
(item no 14)

**Comment by acsiki** [comment]
Indeed. Works like a charm with regular accounts.

Thank you Barry
