### ISSUE TITLE
2FA not used

### ISSUE THREAD

**Issue by core66** [Zimbra-Community/zimbra-foss-2fa#15]
Hi!

Z-Version 8.8.15
Install with Script - OK!
Account Settings 2FA - all Settings done (QR Code and an app password)

First Problem - i can only login without 2FA Code (seems that 2FA is not forced or enabled)
Admin-Console - no 2FA shown.

Pls help me out
ty so much...

greets Chris

**Comment by barrydegraaff** [comment]
Please see [ https://github.com/Zimbra-Community/zimbra-foss-2fa/issues/11 | https://github.com/Zimbra-Community/zimbra-foss-2fa/issues/11 ]

**Comment by core66** [comment]
Hi Barry, i read this...ok i understand the admin login issue, but whats up with the login problem of the normal users?

**Comment by barrydegraaff** [comment]
You have to run the installer 
[ https://github.com/Zimbra-Community/zimbra-foss-2fa#installing | https://github.com/Zimbra-Community/zimbra-foss-2fa#installing ] 

And select all domains you want to enable for 2FA 

Then the users need to set up 2FA in Preferences -> 2FA 

And then it becomes mandatory.

**Comment by core66** [comment]
Barry, iam sorry but i did all this before...all looks good. only the Problem as described in the first post exist.

I can login with my old credentials (without 2FA Code) but NOT with the 2FA Code

![1](https://user-images.githubusercontent.com/37327446/69483976-1ad9fe80-0e2e-11ea-8fe7-25b9b89befb4.PNG)
![2](https://user-images.githubusercontent.com/37327446/69483977-1ad9fe80-0e2e-11ea-8423-776df67befd2.PNG)

**Comment by barrydegraaff** [comment]
Did you log in using the real account name aka [ mailto:user@domain | user@domain.com ] 

not just user or [ mailto:aliasOfuser@domain.com | aliasOfuser@domain.com ] ? 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by barrydegraaff** [comment]
Go to the admin UI and check under you domain what authentication is used: 
https://wiki.zimbra.com/images/thumb/1/1e/Kb-zimbra-activedirectory-004.png/800px-Kb-zimbra-activedirectory-004.png 

It should be External. 

Also check the 
[ https://github.com/Zimbra-Community/zimbra-foss-2fa/blob/master/README-MANUAL-INSTALL.md | https://github.com/Zimbra-Community/zimbra-foss-2fa/blob/master/README-MANUAL-INSTALL.md ] 

For manual installation, do you have a single server set-up? 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by core66** [comment]
Go to the admin UI and check under you domain what authentication is used:
is external

For manual installation, do you have a single server set-up?
yes, but installed over script

**Comment by core66** [comment]
ok we are a step ahead:

User+Pass+vaild 2FA Code = Login OK
User+Pass+wrong 2FA Code = Login FALSE
...but also...
User+Pass = Login OK

hmmm...

**Comment by barrydegraaff** [comment]
You have auth-fallback to local enabled. 

run as Zimbra user: zmprov md example.com zimbraAuthFallbackToLocal FALSE 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0
