### ISSUE TITLE
Zimlet cant generate QR code

### ISSUE THREAD

**Issue by vuvuzela1** [Zimbra-Community/zimbra-foss-2fa#17]
hi guy

i got a problem with zimlet , it cant generate QR code :
![image](https://user-images.githubusercontent.com/58685604/70423163-8ca57f80-1a9f-11ea-9054-810c681208ad.png)

Please help me to solve it !
thank !

**Comment by barrydegraaff** [comment]
Did you use privacyidea installed via our installer? 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0
