### ISSUE TITLE
Support for PrivacyIDEA push tokens

### ISSUE THREAD

**Issue by budachst** [Zimbra-Community/zimbra-foss-2fa#18]
Are you planning on supporting push tokens which are available for privacyIDEA via their iOS and Android app?

**Comment by barrydegraaff** [comment]
No, 

But you can most likely still combine it with Zimbra, in this case you can disable the client Zimlet. 
And expose the PrivacyIdea UI to the user to set-up new tokens. 

Then you can use the push token to log into Zimbra. I have been using HOTP in the same way 
(configured it directly in PrivacyIdea) Then logged on using the ldap proxy to Zimbra.

**Comment by budachst** [comment]
And that would work for all protocols, sine it's transparent to the client. I am not familiar with privacyIDEA yet, but wouldn't it mean, that every account would then need to have a token configured?

**Comment by barrydegraaff** [comment]
Yes, and that part is not support in our Zimlet, that only does TOTP and 'app-passcode' to be set-up. 

It can see and remove any other type of token in privacyidea... so users could still use it for some tasks. 
Just not initial token set-up. 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by budachst** [comment]
Thanks for clarifying.
