### ISSUE TITLE
Include a TAN LIST token type in Zimbra Preferences

### ISSUE THREAD

**Issue by stasou** [Zimbra-Community/zimbra-foss-2fa#19]
Hi, is it feasible to include a TAN LIST token type in Zimbra Interface, in order to have a fallback in case of device loss?

I know the PrivacyIdea API supports this, but it would require modifying the Zimlet in order to be able to include this.

**Comment by barrydegraaff** [comment]
I am not planning on it, as people can already add mutliple totp tokens as fall-back and also use passcodes.
