### ISSUE TITLE
Install On Zimbra Multi Server

### ISSUE THREAD

**Issue by rizkypratama01** [Zimbra-Community/zimbra-foss-2fa#2]
Hi,

I want to install 2FA on Zimbra Multi Server, I have 2 mailbox server, to setup it in only one mailbox or in all mailboxes?

My issue, I have setup that on 1 mailbox, but not work, show error LDAP Connection Timed out, after that I have generated the token, it's already connected to the google authenticator, but cannot login to webmail.

Can you explain in more detail about installing on Zimbra Multi Server? what things must be prepared?

**Comment by barrydegraaff** [comment]
I would recommend installing the Docker on a separate virtual machine, and not put it on a mailbox server if you have a multiserver Zimbra. So purge all now, and set it up on a dedicated machine. Removal steps are here: https://github.com/Zimbra-Community/zimbra-foss-2fa/blob/master/privacyidea/Dockerfile#L1

Next thing to do, is check if you see users in your PrivacyIDEA ui? Did you set-up the policies? And most important: What are your results from step 9 in the install guide?

Try and see if it works by doing LDAP searches

You must append to OTP code to the password like so:

      ldapsearch -x -H ldap://zimbraserver:389 -D uid=user2,ou=people,dc=zimbradev,dc=barrydegraaff,dc=tk -w "PASSWORD HERE" "mail=*"
      ldapsearch -x -H ldap://172.18.0.2:1389 -D uid=user2,ou=people,dc=zimbradev,dc=barrydegraaff,dc=tk -w "PASSWORD HERE***OTP HERE***" "mail=*"

If it does not work, check if PrivacyIDEA works directly using the API 

      curl -d "user=user1&pass=testabc387223" -X POST https://zimbraserver:5000/validate/check or from the Zimbra server 
      curl -d "user=user1&pass=testabc944412" -X POST http://172.18.0.2:8000/validate/check.

Since you are doing a multiserver, the ldapsearch should work from both your zimbra mailbox servers, also you want to run the docker with the ldap port exposed:

      docker run --init --net zimbradocker --ip 172.18.0.2 -p 5000:443 -p 1389:1389 --name privacyidea --restart=always -v privacyidea_data:/etc/privacyidea -v privacyidea_log:/var/log/privacyidea -v privacyidea_mariadb:/var/lib/mysql -v /opt/privacyIdeaLDAPProxy:/opt/privacyIdeaLDAPProxy -d zetalliance/privacy-idea:latest

**Comment by rizkypratama01** [comment]
For step 9, I have an error when authenticate to ldap privacyidea

ldapsearch -x -H ldap://192.168.8.1:1389 -D uid=user1,ou=people,dc=domain,dc=id -w "mypassword***myotp***" "mail=*"
ldap_bind: Invalid credentials (49)
	additional info: Failed to authenticate.


But when authenticate to LDAP Zimbra with this command, success
ldapsearch -x -H ldap://192.168.8.21:389 -D uid=user1,ou=people,dc=domain,dc=id -w "mypassword" "mail=*"

I have an enroll the token from Enroll Token on Privacyidea


After that, I have check for this command, show message "wrong otp pin"

curl -k -d "user=user1&pass=rahasia" -X POST https://192.168.8.1:5000/validate/check
{"jsonrpc": "2.0", "signature": "3249958994819358086028846082952911713407535803586779900770270106887992359793618110475516466800216786647889786796278405502996404785074832976393023219694911260360511283293892095962322736590931417168613599589221960879780299780875036223024399572082501078345385998967464825449572968727139561496762553120043966414625988007022929430978196197296449846752649861826589332173869623323170851209617114374190314520005858330812189746112707886399558262940925550160030255245810088881868641789413130788302825021809352145833842140602827285952460971093059661775062967168663721058737259389397384901340032484080733080574641154647316132890", "detail": {"message": "wrong otp pin", "threadid": 140715142616896}, "versionnumber": "2.23.4", "version": "privacyIDEA 2.23.4", "result": {"status": true, "value": false}, "time": 1551856846.50197, "id": 1}

**Comment by rizkypratama01** [comment]
For case above has been solved, thanks for your tutorial

But for trust the device still not yet

In the future, maybe this feature might be added

**Comment by barrydegraaff** [comment]
What do you mean with `But for trust the device still not yet`?

In case you cannot add `app passcodes`, please make sure to...

**Enter your password followed by the code as password on your app**

So it is password + passcode => into the password field
