### ISSUE TITLE
Request user confirmation upon deleting a token

### ISSUE THREAD

**Issue by stasou** [Zimbra-Community/zimbra-foss-2fa#20]
Hello,

It has been reported that users have accidentally erased tokens from the web interface of Zimbra.

Adding a simple javascript confirmation before actually deleting a token (it currently happens with a plain simple click) would help increase the safety against accidental deletion of tokens.

**Comment by barrydegraaff** [comment]
I can confirm this is indeed an issue that should be fixed.

**Comment by barrydegraaff** [comment]
has been added, to update do:

      cd /tmp
      wget https://github.com/Zimbra-Community/zimbra-foss-2fa/releases/download/0.0.2/tk_barrydegraaff_2fa.zip -O /tmp/tk_barrydegraaff_2fa.zip
      chmod zimbra:zimbra  /tmp/tk_barrydegraaff_2fa.zip
      su zimbra -c "/opt/zimbra/bin/zmzimletctl deploy /tmp/tk_barrydegraaff_2fa.zip"
