### ISSUE TITLE
Cannot connect to zentyal directory service

### ISSUE THREAD

**Issue by takatux** [Zimbra-Community/zimbra-foss-2fa#22]
i'm using zentyal which uses samba as directory service, the authentication using the API is fine. but when i tried the ldapsearch i received invalid user.

i tried 
`curl -d "user=user&pass=mypass" -X POST http://172.18.0.2:8000/validate/check` is running well

here is my config.ini
```
[ldap-backend]
endpoint = tcp:host=10.37.37.9:port=389
[service-account]
dn = "CN=sa user,CN=Users,DC=zentyal-domain,DC=lan"
password = mysapass
```

i followed the manual installation, what can i do to fix this?
big thanks.

**Comment by barrydegraaff** [comment]
usually you will have to debug using LDAP tools, check what attribute is used for the username AND password. Take a look at how the password is hashed and if the username includes the domain aka barry or barry@example.com

Probably best to first install a test Zimbra server and run the automated installed, test if it works and compare with your LDAP.
