### ISSUE TITLE
Error when generate QR code

### ISSUE THREAD

**Issue by vuvuzela1** [Zimbra-Community/zimbra-foss-2fa#23]
Hi,
An error occurred when I created the QR code:
![image](https://user-images.githubusercontent.com/58685604/82401931-596f0f80-9a85-11ea-94d3-8a7cd2061d30.png)
I have configured the API URL in the extension file
Please help me

**Comment by barrydegraaff** [comment]
I just verified zimbra-foss-2fa on Ubuntu 18.04.5 - did you use the automated installer?
