### ISSUE TITLE
Help! 2fa installation locked me out

### ISSUE THREAD

**Issue by D4nzi** [Zimbra-Community/zimbra-foss-2fa#24]
Hello,

i just used your installer on my server, now i am locked out. I can not log in to the Mailbox, the Admin console etc. i tried to disable/undeploy the zimlets

-zmzimletctl listZimlets
-zmzimletctl undeploy zimlet_name

and also i undeployed the docker (https://askubuntu.com/questions/935569/how-to-completely-uninstall-docker)

but still there is the 2fa in the login screen and i can not login into those mailboxes.
Even IMAP is not working

What can i do to roll back to the old situation.

Andreas

**Comment by barrydegraaff** [comment]
zmprov md example.com zimbraAuthMech "zimbra"

should turn back the internal auth mechanism

**Comment by D4nzi** [comment]
> zmprov md example.com zimbraAuthMech "zimbra"
> 
> should turn back the internal auth mechanism

that worked to access the mailbox. but how can i deinstall everything and roll back the installation?

**Comment by barrydegraaff** [comment]
Open this file:

/opt/zimbra/jetty/webapps/zimbra/h/changepass

And remove the part that looks like this: https://raw.githubusercontent.com/Zimbra-Community/zimbra-foss-2fa/master/patches/changepass-patch.js

**Comment by rogierm** [comment]
> Hello,
> 
> i just used your installer on my server, now i am locked out. I can not log in to the Mailbox, the Admin console etc. i tried to disable/undeploy the zimlets
> 
> -zmzimletctl listZimlets
> -zmzimletctl undeploy zimlet_name
> 
> and also i undeployed the docker (https://askubuntu.com/questions/935569/how-to-completely-uninstall-docker)
> 
> but still there is the 2fa in the login screen and i can not login into those mailboxes.
> Even IMAP is not working
> 
> What can i do to roll back to the old situation.
> 
> Andreas

Hi Andreas, 
Do you know what caused the issue when you enabled the privacyidea integration? 
This could help other users of the project. 

Thanks, 
rogier
