### ISSUE TITLE
2fa does not appear in Account Preferences in Zimbra

### ISSUE THREAD

**Issue by jacksonvld** [Zimbra-Community/zimbra-foss-2fa#25]
Gentlemen,
I did the whole installation and everything went well. Queries by ldapsearch performed successfully. However, the option "2fa Account Security" does not appear in the account preferences.

**Comment by barrydegraaff** [comment]
Check the guides: https://github.com/Zimbra-Community/zimbra-foss-2fa/blob/master/README-MANUAL-INSTALL.md

Most likely the Zimlet is not enabled in the CoS (Class of service) or your account (check Accounts -> Zimlets in the Admin UI)
