### ISSUE TITLE
Error to add token and app passcode via Zimbra web interface

### ISSUE THREAD

**Issue by alexandre1984rj** [Zimbra-Community/zimbra-foss-2fa#29]
All tokens can be added/removed via PrivacyIDEA web interface but not at Zimbra Preferences Tab.
I have no problems at all to login with TOTP token also.
But when I'm trying to generate the token at Zimbra Preferences Tab the following error apears: 

 {"jsonrpc": "2.0", "signature": "15126913567806166074801192942115305060755304799919958057397736721789740908717533269584552714353314278430185423579198248137263460425808640800896492589833513348230200843103435151540935200618005348503222951188064613743680665297385343230433985477019218526431004964801389739289779745025060022345674097544890505726410367433959762911804815625794334147008701706966961899896878274230366502261042031965459901962290877657653467859036300221907021057495566970208016529144783098565657283896576879012901088849693909090069265894083156410097776259170853365172920032634322590742425552992799367128750628965381420978149966904877641071977", "detail": null, "version": "privacyIDEA 2.23.4", "result": {"status": false, "error": {"message": "ERR904: The user can not be found in any resolver in this realm!", "code": 904}}, "time": 1613503297.767135, "id": 1} 

A similar error appears after trying to generate the app passcode also:

TypeError: o.detail is null

**Comment by alexandre1984rj** [comment]
![image](https://user-images.githubusercontent.com/20284098/108113285-18d50e80-7076-11eb-8a07-81a9989a64dc.png)

**Comment by barrydegraaff** [comment]
I just verified it still works, did you run the automated installer?

**Comment by alexandre1984rj** [comment]
I just ran the manual installation. It was working perfectly then I don't know why it now accepts the login without the token even after disabling it on Zimbra. I was figuring out that would be the version update, Patch etc. But even installing on Zimbra previous versions the error occurs.

**Comment by alexandre1984rj** [comment]
Problem solved after applying the last patch
