### ISSUE TITLE
Trust a computer/device

### ISSUE THREAD

**Issue by imanudin11** [Zimbra-Community/zimbra-foss-2fa#3]
Hello,

Is it possible to trust a computer/devices like this: https://wiki.zimbra.com/wiki/Zimbra_Two-factor_authentication#How_to_trust_a_computer.2Fdevice

BR,
AI

**Comment by barrydegraaff** [comment]
Yes, see the demo video. In the webUI go to preferences -> 2fa -> app token

**Comment by imanudin11** [comment]
Hello,
I mean "trust this computer" after login from webmail :) and yes i am used app token to my mobile devices

**Comment by barrydegraaff** [comment]
No, I do not believe in that kind of security

**Comment by imanudin11** [comment]
Thanks for your information. Your project is awesome 👍
