### ISSUE TITLE
Latest zimbra patch

### ISSUE THREAD

**Issue by mailanetworks** [Zimbra-Community/zimbra-foss-2fa#31]
Hello,

After last night's patches released by zimbra, the two factor authentication stopped working.

I have reinstalled without luck.

Thanks,

**Comment by barrydegraaff** [comment]
zimbra version?

**Comment by mailanetworks** [comment]
Hi,

Zimbra 8.8.15_GA_4007 (build 20210209202107)

Thanks,

**Comment by barrydegraaff** [comment]
Rerunning the installer should work.
