### ISSUE TITLE
Question regarding certificate copy in install script

### ISSUE THREAD

**Issue by Georg311** [Zimbra-Community/zimbra-foss-2fa#4]
In the install script the zimbra certificates are copied to a place where the volume for privacyidea config/certificates are stored

https://github.com/Zimbra-Community/zimbra-foss-2fa/blob/3cc7ace4a207402d3d31e552c46db2e1020e66c3/2fa-installer.sh#L144-L148

Isn't this a risk when changing certificates, or when they expire.
You'd have to do the install process again (or copy the certificates manually) so privacyidea has the possibility to even get the new certificates.

Wouldn't it be better to just link the zimbra certificates as single volumes (read only with :ro), so with a container reboot so privacyIDEA would then use the correct certificates?
e.g.

Depending on certificate used server/server.key:
```shell
# first one for the config.ini
-v /opt/privacyIdeaLDAPProxy/$OPTION2FAINST:/opt/privacyIdeaLDAPProxy
# second one for server key
-v /opt/zimbra/ssl/zimbra/server/server.key:/opt/privacyIdeaLDAPProxy/$OPTION2FAINST/server.key:ro 
# third one for public cert
-v /opt/zimbra/conf/nginx.crt:/opt/privacyIdeaLDAPProxy/$OPTION2FAINST/server.crt:ro
```

or commercial cert commercial/commercial.key:
```
# first one for the config.ini
-v /opt/privacyIdeaLDAPProxy/$OPTION2FAINST:/opt/privacyIdeaLDAPProxy
# second one for server key
-v /opt/zimbra/ssl/zimbra/commercial/commercial.key:/opt/privacyIdeaLDAPProxy/$OPTION2FAINST/server.key:ro 
# third one for public cert
-v /opt/zimbra/conf/nginx.crt:/opt/privacyIdeaLDAPProxy/$OPTION2FAINST/server.crt:ro
```

because you can't map both .key files to a single server.key file.

**Comment by barrydegraaff** [comment]
Yes this is most definitely a better way to do it.

You can send a PR or I will change the code somewhere later this week.

Thanks!

**Comment by barrydegraaff** [comment]
Perhaps one solution would be to put 2 symlinks in /opt/privacyIdeaLDAPProxy pointing to the certs and then do the readlink option as discussed here:

https://stackoverflow.com/questions/38485607/mount-host-directory-with-a-symbolic-link-inside-in-docker-container

**Comment by Georg311** [comment]
Wouldn't the "readlink" approach be quite similar to the "mounting it from the actual filepath" approach?

Problem is, with symlinks everything is a workaround in docker.
So not using a symlink between host and docker container and mounting via a volume seems to be  the best way in my opinion? 

I guess it come's down to how you like to have it

I've created the pull request #6 , please tell me if that would be an okay way to handle that for you

**Comment by barrydegraaff** [comment]
PR merged
