### ISSUE TITLE
password option does not show?

### ISSUE THREAD

**Issue by killmasta93** [Zimbra-Community/zimbra-foss-2fa#40]
Hi,
Recently installed on ubuntu 18 with zimbra 8.8.15 when i create a new account it shows no password dialog

![image](https://user-images.githubusercontent.com/13953629/116013895-2e2b6380-a5f8-11eb-9d5b-8317a0000549.png)

Thank you

**Comment by killmasta93** [comment]
bump anyone?

**Comment by vnngoanhtuan** [comment]
Hi,

You need to use command to create new user in this case as we changed authentication from internal to external.
- Note: some limited on privacyidea: You are using privacyIDEA with more than 50 users.

Thanks,
Tuan Ngo

**Comment by killmasta93** [comment]
Thank you for the reply, what i realized is that i create the user first, then after i create the user i right click and change password it seemed to work but wanted to make sure its a not a bug

**Comment by vnngoanhtuan** [comment]
Hi,

This is not a bug as You change authentication from zimbra ldap internal (389) to privacyidea ldap external (1389) so password in create new user is disabled.

- privacyidea  is only support max 50 users for using, if more than 50 users we need to buy subscriptions (NOT GOOD FOR ME, ...)

- privacyIDEA Enterprise Edition Cost: https://netknights.it/en/produkte/privacyidea/
---
You are using privacyIDEA with more than 50 users.

Thank you for your trust!

For the productive enterprise use we recommend the privacyIDEA Enterprise Edition.

NetKnights provides the privacyIDEA Enterprise Edition including Support and Service Level Agreements. Moreover NetKnights provides services, consultancy and payed programming of new features.
--

Thanks,
Tuan Ngo

**Comment by killmasta93** [comment]
o boy i didnt know is there another 2fa? option?
