### ISSUE TITLE
User Login Issue

### ISSUE THREAD

**Issue by zafran-ullah** [Zimbra-Community/zimbra-foss-2fa#43]
Zimbra-FOSS-2FA has been successfully integrated but it is working for email accounts created after integration. What can be done for already created email accounts?

**Comment by zafran-ullah** [comment]
The log "tail -f /var/lib/docker/volumes/privacyidea_log/_data/privacyidea.log" shows following

[INFO][privacyidea.lib.user:230] user u'ABC' found in resolver u'zimbra'
[INFO][privacyidea.lib.user:346] User u'ABC' from realm u'zimbra' tries to authenticate
[INFO][privacyidea.lib.user:346] User u'ABC' from realm u'zimbra' tries to authenticate
[INFO][privacyidea.lib.user:346] User u'ABC' from realm u'zimbra' tries to authenticate
[INFO][privacyidea.lib.user:346] User u'ABC' from realm u'zimbra' tries to authenticate
[WARNING][privacyidea.lib.resolvers.LDAPIdResolver:323] failed to check password for u'70615cf2-3cf3-103b-93b9-9525fd9948c3'/u'uid=ABC,ou=people,dc=xyz,dc=com,dc=pk': Exception('Wrong credentials',)
[INFO][privacyidea.lib.user:359] user User(login=u'ABC', realm=u'zimbra', resolver=u'zimbra') failed to authenticate.

**Comment by barrydegraaff** [comment]
there should not be a difference between new and old users, recheck the user resolver and do a manual ldap search with the users credentials
