### ISSUE TITLE
User Login on other clients than Web Client

### ISSUE THREAD

**Issue by B-LUC** [Zimbra-Community/zimbra-foss-2fa#44]
I LOVE this add-on - it makes MFA so easy with the web client.  However, I have users with desktop and smartphone clients which don't have a field for a second authentication factor - how can I have them use the MFA token from FreeOTP?

**Comment by B-LUC** [comment]
I created an AppCode and try to use it with Thunderbird (for now) - all I get is "login failed" in /var/lib/docker/volumes/<mydomain>_privacyidea_log/_data/privacyidea.log (I can make the raw log excerpt available is necessary).

**Comment by barrydegraaff** [comment]
Enter your password followed by the AppCode as password on desktop client as the Zimlet mentions.
