### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by mikeykau** [Zimbra-Community/zimbra-foss-2fa#5]
Hi,
I've tried to use this with Zimbra 8.8.11 on Ubuntu 16.04.10.
I'm running IPv6 and IPv4, the install script 2fa-installer.sh fails at the LDAP IP section.
It appears to include the IPv4 address, along with the first field of my IPv6 address. i.e. "172.17.1.10 2001" in the variable.
I've set zimbraIPMode to IPv4, but still had to hard code my IPv4 address, by replacing LDAPIP=$(netstat -tulpn | grep :389 | awk '{ print $4 }' | awk -F  ":" '{ print $1 }' | grep -v 127.0.0.1)
with LDAPIP=172.17.1.10
This allows the install script to continue, although when setting zimbraIPMode back to 'both' the user login page will not load. I can't see any entries in any log files to point me in the right direction.
I'm happy to help test anything as I have this on a development system with a snapshot of the server prior to installing zimbra-foss-2fa that I have been rolling back to in each attempt.

**Comment by barrydegraaff** [comment]
Okay, other than a javascript patch, the logon screen is build-in Zimbra stuff, so if that loads or not, should be a zimbra configuration issue.

Since you run both ipv4 and ipv6 it is probably just a failed regex in the installer.

What is the output of the installer if we change the regex to:
LDAPIP=$(netstat -tulpn | grep :389 | awk '{ print $4 }' | awk -F ":" '{ print $1 }' | grep -v 127.0.0.1 | grep -v tcp6)

**Comment by mikeykau** [comment]
Hi,
That is the same output as before;
172.17.1.10 2001

The logon screen not loading may have been a furphy, as it is now loading after several browser refreshes.

Thanks,
Michael

**Comment by barrydegraaff** [comment]
Please provide the output of `netstat -tulpn`

**Comment by mikeykau** [comment]
Hi,
Here is the output, also I mentioned 172.17.1.10 above, I was obfuscating the IP, it is 10.255.10.40 as can be seen below. 

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:23232         0.0.0.0:*               LISTEN      19306/perl      
tcp        0      0 127.0.0.1:23233         0.0.0.0:*               LISTEN      19308/perl      
tcp        0      0 10.255.10.40:993        0.0.0.0:*               LISTEN      19282/nginx.conf
tcp        0      0 10.255.10.40:995        0.0.0.0:*               LISTEN      19282/nginx.conf
tcp        0      0 10.255.10.40:389        0.0.0.0:*               LISTEN      17435/slapd     
tcp        0      0 127.0.0.1:10663         0.0.0.0:*               LISTEN      18908/zmlogger: zmr
tcp        0      0 127.0.0.1:10024         0.0.0.0:*               LISTEN      19367/amavisd (mast
tcp        0      0 127.0.0.1:10026         0.0.0.0:*               LISTEN      19367/amavisd (mast
tcp        0      0 0.0.0.0:587             0.0.0.0:*               LISTEN      19825/master    
tcp        0      0 0.0.0.0:11211           0.0.0.0:*               LISTEN      19263/memcached 
tcp        0      0 127.0.0.1:3310          0.0.0.0:*               LISTEN      19579/clamd     
tcp        0      0 10.255.10.40:110        0.0.0.0:*               LISTEN      19282/nginx.conf
tcp        0      0 10.255.10.40:143        0.0.0.0:*               LISTEN      19282/nginx.conf
tcp        0      0 127.0.0.1:10032         0.0.0.0:*               LISTEN      19367/amavisd (mast
tcp        0      0 10.255.10.40:80         0.0.0.0:*               LISTEN      19282/nginx.conf
tcp        0      0 0.0.0.0:465             0.0.0.0:*               LISTEN      19825/master    
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      18539/unbound   
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1302/sshd       
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      19825/master    
tcp        0      0 10.255.10.40:443        0.0.0.0:*               LISTEN      19282/nginx.conf
tcp6       0      0 :::7071                 :::*                    LISTEN      19026/java      
tcp6       0      0 :::7072                 :::*                    LISTEN      19026/java      
tcp6       0      0 :::993                  :::*                    LISTEN      19282/nginx.conf
tcp6       0      0 :::7073                 :::*                    LISTEN      19026/java      
tcp6       0      0 :::995                  :::*                    LISTEN      19282/nginx.conf
tcp6       0      0 ::1:7171                :::*                    LISTEN      17455/java      
tcp6       0      0 :::7780                 :::*                    LISTEN      19625/httpd     
tcp6       0      0 2001:44b8:3138:c570:389 :::*                    LISTEN      17435/slapd     
tcp6       0      0 :::5222                 :::*                    LISTEN      19026/java      
tcp6       0      0 :::7110                 :::*                    LISTEN      19026/java      
tcp6       0      0 :::7143                 :::*                    LISTEN      19026/java      
tcp6       0      0 ::1:10024               :::*                    LISTEN      19367/amavisd (mast
tcp6       0      0 ::1:10025               :::*                    LISTEN      19825/master    
tcp6       0      0 ::1:10026               :::*                    LISTEN      19367/amavisd (mast
tcp6       0      0 ::1:7306                :::*                    LISTEN      18898/mysqld    
tcp6       0      0 ::1:10027               :::*                    LISTEN      19825/master    
tcp6       0      0 :::587                  :::*                    LISTEN      19825/master    
tcp6       0      0 :::11211                :::*                    LISTEN      19263/memcached 
tcp6       0      0 ::1:10028               :::*                    LISTEN      19825/master    
tcp6       0      0 ::1:10029               :::*                    LISTEN      19825/master    
tcp6       0      0 ::1:10030               :::*                    LISTEN      19825/master    
tcp6       0      0 ::1:3310                :::*                    LISTEN      19579/clamd     
tcp6       0      0 :::110                  :::*                    LISTEN      19282/nginx.conf
tcp6       0      0 :::143                  :::*                    LISTEN      19282/nginx.conf
tcp6       0      0 ::1:10032               :::*                    LISTEN      19367/amavisd (mast
tcp6       0      0 :::80                   :::*                    LISTEN      19282/nginx.conf
tcp6       0      0 :::8080                 :::*                    LISTEN      19026/java      
tcp6       0      0 :::465                  :::*                    LISTEN      19825/master    
tcp6       0      0 ::1:8465                :::*                    LISTEN      19599/opendkim  
tcp6       0      0 :::7025                 :::*                    LISTEN      19026/java      
tcp6       0      0 :::5269                 :::*                    LISTEN      19026/java      
tcp6       0      0 ::1:53                  :::*                    LISTEN      18539/unbound   
tcp6       0      0 :::22                   :::*                    LISTEN      1302/sshd       
tcp6       0      0 :::25                   :::*                    LISTEN      19825/master    
tcp6       0      0 :::7993                 :::*                    LISTEN      19026/java      
tcp6       0      0 :::443                  :::*                    LISTEN      19282/nginx.conf
tcp6       0      0 :::7995                 :::*                    LISTEN      19026/java      
tcp6       0      0 :::8443                 :::*                    LISTEN      19026/java      
udp        0      0 127.0.0.1:53            0.0.0.0:*                           18539/unbound   
udp6       0      0 :::43867                :::*                                19026/java      
udp6       0      0 :::44153                :::*                                17455/java      
udp6       0      0 ::1:53                  :::*                                18539/unbound

**Comment by barrydegraaff** [comment]
Ahh, I think I may have had a bad day.

I think this should work, can you confirm, so I can put it back in the installer, thanks!

LDAPIP=$(netstat -tulpn | grep -v tcp6 | grep -v 127.0.0.1 | grep :389 | awk '{ print $4 }' | awk -F ":" '{ print $1 }')

**Comment by mikeykau** [comment]
Hi,
Yes thank you, I rolled back and ran the installer with the modification and it worked.

Cheers,
Michael

**Comment by barrydegraaff** [comment]
Thanks, changes committed
