### ISSUE TITLE
Zimbra with AD integration 

### ISSUE THREAD

**Issue by biswajitban** [Zimbra-Community/zimbra-foss-2fa#50]
Hi 
Was specifically looking to implement this on  Zimbra 8.8.15 with  Samba 4.x AD . I already have a setup on zimbra integrated with AD as external LDAP . Can I use this in my scenario ? if yes , Please given pointers . I search the documentation , it say supports AD but no document pointer . Please help .

Thanks for the wonderful product and concept .
TIA 
Biswajit

**Comment by barrydegraaff** [comment]
Zimbra-FOSS-2FA needs to talk to an LDAP, you can set-it up by following the steps in 
https://github.com/Zimbra-Community/zimbra-foss-2fa/blob/master/README-MANUAL-INSTALL.md

You will probably want to avoid using the docker images and auto installer, as those are not created for you set-up. Please see https://privacyidea.readthedocs.io/en/latest/installation/ubuntu.html

The Zimbra extension and Zimlet will work with your self installed PrivacyIDEA and Samba.
