### ISSUE TITLE
Token confuses browser's store password feature

### ISSUE THREAD

**Issue by stasou** [Zimbra-Community/zimbra-foss-2fa#8]
Hello,

after having tested the basic functionality of this great plugin, I noticed that the token gets appended to the password, as it should actually, but this is done prior to form submission.

This leads to the browser detecting a different password than the one stored, requesting to update the existing saved entry.

The ideal scenario would be to somehow submit the concatenated string (password + token) without the browser picking the change.

Not a vital issue, a nice to have though.

Keep up the good work.

Kind regards,
Stavros

**Comment by stasou** [comment]
Following up, I managed to go through this by doing some patchwork (not ideal, but this could be augmented into a proper solution):

All changes below are done of `/opt/zimbra/jetty/webapps/zimbra/public/login.jsp`

Changed some attributes of the password field and added a hidden field:
```
                                <td><input id="password" name="nootppass" autocomplete="off" class="zLoginField" type="password" value="" size="40" maxlength="${domainInfo.webClientMaxInputBufferLength}"/>
                                    <input id="password_otp" autocomplete="off" name="password" type="hidden" value=""/></td>
```

Then, change a line that causes an error (focusing on password, so I focus on `nootppass`
```
function onLoad() {
        var loginForm = document.loginForm;
        if (loginForm.username) {
                if (loginForm.username.value != "") {
                        loginForm.nootppass.focus(); //if username set, focus on password
                }
                else {
                        loginForm.username.focus();
                }
        }
[...]
```

And finally, change the value of the hidden field prior to submitting:

```
function zetaDoLogin(){
   //Submit the form with the OTP value
   document.getElementById('password_otp').value = document.getElementById('password').value + document.getElementById('zeta-otp').value;
   var originalSubmitButton=document.querySelectorAll('input[type=submit]');
   originalSubmitButton[0].click();
}
```

**Comment by barrydegraaff** [comment]
It will be a bit difficult to maintain, as it needs changes in various places in login.jsp. 

Right now, each time Zimbra upgrades, you will need to re-patch login.jsp. 


And the installer uses some regex magic to apply the patch on a single location. 


Doing the suggested patch via the installer will be a pain. So the only way to work-around 
it, is to fork the entire login.jsp and maintain it from this Git repo. Only then I have to 
track closely the upstream changes to login.jsp. Since there may be security updates 
in there. 


So that is all less then ideal. It is a shame the HTML standard does not provide 
a way to disable the storing of passwords, which is poor security IMHO anyways. 


I think this patch could go in a wiki page, with some clear instructions for those people that want it.

**Comment by stasou** [comment]
You are most certainly right.

I did however try a couple of things and I think there is way to make this happen only by using the patching method you already provide.

I ended up doing the following, which actually works, and everything is added below the `/*Start Zeta Alliance Zimbra FOSS 2FA patch*/` line.

So, here it goes. Perhaps I should do this with a pull request, but I am not quite sure how to do this (not too experienced).

```
<script>
/*Start Zeta Alliance Zimbra FOSS 2FA patch*/

/* On your Zimbra server your need to put this code in the login screen.
 * open /opt/zimbra/jetty/webapps/zimbra/public/login.jsp
 * And add it before the final < / script > tag.
 * */

/* replace some login fields' attributes */
window.onLoad = function() {
        setTimeout( function() {
                var passField = document.getElementById('password');
                passField.setAttribute('name','nopass');
                var lForm = document.querySelector('form');
                var newNode = document.createElement('input');
                newNode.setAttribute('name', 'password');
                newNode.setAttribute('type', 'hidden');
                newNode.setAttribute('id', 'password_with_otp');
                lForm.appendChild(newNode);
        }, 100);
}
```

And then, a small change on zetaDoLogin:

```
function zetaDoLogin(){
   //Submit the form with the OTP value
   document.getElementById('password_with_otp').value = document.getElementById('password').value + document.getElementById('zeta-otp').value;
   var originalSubmitButton=document.querySelectorAll('input[type=submit]');
   originalSubmitButton[0].click();
}     
```

This works fine for me, and something similar, I guess, should be done on change password form.

**Comment by barrydegraaff** [comment]
Yeah that is a lot better, did you try it without the onLoad/setTimeout? 

While it probably works, maybe we can do it without onLoad/setTimeout 
to make it more reliable. 

If not, I will test and merge this tomorrow.

**Comment by stasou** [comment]
I haven't tested it without it actually.

The only reason I put the timeout is because there is already a body onLoad handler. So, I guess, timeout can safely be removed, also considering the fact that the new function does not mangle with the existing input ids.

If this turns out to be ok, I am glad to have been of any assistance.

Regards,
Stavros

**Comment by stasou** [comment]
Somehow I have done something wrong here, no need to onLoad, it does not work like that. All you have to do is just run the commands. The dom is there, so the commands will run in every case.

Function and Timeout are gone:

```
/* replace some login fields' attributes */
    var passField = document.getElementById('password');
    passField.setAttribute('name','nopass');
    var lForm = document.querySelector('form');
    var newNode = document.createElement('input');
    newNode.setAttribute('name', 'password');
    newNode.setAttribute('type', 'hidden');
    newNode.setAttribute('id', 'password_with_otp');
    lForm.appendChild(newNode);
```

**Comment by barrydegraaff** [comment]
Based on your comment I tried it like so:
https://gist.github.com/barrydegraaff/3ebcef59667c338a2251400d5c8447e3

But that throws a `Uncaught TypeError: loginForm.password.focus is not a function`

And then it does no longer submit, so I cannot logon (not by pressing enter or clicking the login button)

So perhaps you can do some more trial and error.

**Comment by stasou** [comment]
For submission, you are still missing the updated zeta submitter:

```
function zetaDoLogin(){
   //Submit the form with the OTP value
   document.getElementById('password_with_otp').value = document.getElementById('password').value + document.getElementById('zeta-otp').value;
   var originalSubmitButton=document.querySelectorAll('input[type=submit]');
   originalSubmitButton[0].click();
} 
````

It works ok for me. No warnings at all, submission works ok.

Let me show you a gist with the current full functionality. This is the login.jsp from zimbra 8.8.11, with the patch

https://gist.github.com/stasou/a8a81e7d64219c492c92e9b17d9209de

**Comment by barrydegraaff** [comment]
Thanks, I have merged based on your gist.

**Comment by stasou** [comment]
This is great news.

This has been an absolutely positive experience for me.

Keep up the good work.

Kind regards,
Stavros

**Comment by barrydegraaff** [comment]
Thanks for the compliment, I added contact info and donation possibilities to the readme :-p

**Comment by barrydegraaff** [comment]
Unfortunately I have rolled back this changes, because of a rather severe security issue it creates.

After logging in using the patches login.jsp, one can find the users password using the browser console (F12) and than drop the following in console:
AjxUtil.formatUrl ({}); 

This will return:
"https://zimbradev/?nopass=YOURPASSWORDGOESHERE"

**Comment by stasou** [comment]
Hi Barry, this is an issue that I am unaware of, but it can be easily solved, simply by removing the name attribute from the password field (thus it does not get submitted).

By only changing this line:

```
        var passField = document.getElementById('password');
/*        Yikes! Some library stores this                    */
/*        passField.setAttribute('name','nopass');    */
/*        Better to completely clear the name attribute used by the form for submission              */
        passField.setAttribute('name','');
        var lForm = document.querySelector('form');
        var newNode = document.createElement('input');
        newNode.setAttribute('name', 'password');
        newNode.setAttribute('type', 'hidden');
        newNode.setAttribute('id', 'password_with_otp');
        lForm.appendChild(newNode);
```

**Comment by barrydegraaff** [comment]
fixed and merged new patch.
